name: 'dbt_fabric_demo'
version: '1.0.0'
config-version: 2

profile: 'dbt_fabric_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  materialized: view
  dbt_fabric_demo:
    example:
      marts:
        materialized: table
      schema: example
    jaffle_shop:
      marts:
        materialized: table
      schema: jaffle_shop
    new_york_taxi:
      marts:
        materialized: table
      schema: new_york_taxi
