name: 'dbt_fabric_demo'
version: '1.0.0'
config-version: 2

profile: 'dbt_fabric_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_fabric_demo:
    example:
      +materialized: view
      +schema: example
    jaffle_shop:
      +schema: jaffle_shop
      +materialized: table
